export const GET_CHARACTERS_START = 'GET_CHARACTERS_START';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAIL = 'GET_CHARACTERS_FAIL';
export const POST_USER_CHOICES_SUCCESS = 'POST_USER_CHOICES_SUCCESS';
export const POST_USER_CHOICES_START = 'POST_USER_CHOICES_START';
export const POST_USER_CHOICES_FAIL = 'POST_USER_CHOICES_FAIL';
export const UPDATE_CHARACTER_STATUS = 'UPDATE_CHARACTER_STATUS';
export const CHOICES_DONE = 'CHOICES_DONE';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";

export const GET_USER_CHOICES_START = 'GET_USER_CHOICES_START';
export const GET_USER_CHOICES_SUCCESS = 'GET_USER_CHOICES_SUCCESS';
export const GET_USER_CHOICES_FAIL = 'GET_USER_CHOICES_FAIL';

export const GET_BACK_CHARACTERS_START = 'GET_BACK_CHARACTERS_START';
export const GET_BACK_CHARACTERS_SUCCESS = 'GET_BACK_CHARACTERS_SUCCESS';
export const GET_BACK_CHARACTERS_FAIL = 'GET_BACK_CHARACTERS_FAIL';
export const PATCH_CHARACTER_STATUS_START = 'PATCH_CHARACTERS_STATUS_START';
export const PATCH_CHARACTER_STATUS_SUCCESS = 'PATCH_CHARACTERS_STATUS_SUCCESS';
export const PATCH_CHARACTER_STATUS_FAIL = 'PATCH_CHARACTERS_STATUS_SUCCESS';



