export const GET_CHARACTERS = 'GET_CHARACTERS';
export const UPDATE_CHARACTERS_STATUS = 'UPDATE_CHARACTERS_STATUS';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_USER_CHOICES = 'GET_USER_CHOICES';
export const POST_USER_CHOICES = 'POST_USER_CHOICES';
