export const GET_CHARACTERS_START = 'GET_CHARACTERS_START';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAIL = 'GET_CHARACTERS_FAIL';
export const POST_USER_CHOICES_SUCCESS = 'POST_USER_CHOICES_SUCCESS';
export const POST_USER_CHOICES_START = 'POST_USER_CHOICES_START';
export const POST_USER_CHOICES_FAIL = 'POST_USER_CHOICES_FAIL';
export const UPDATE_CHARACTER_STATUS = 'UPDATE_CHARACTER_STATUS';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";

export const GET_USER_CHOICES = 'GET_USER_CHOICES';
